# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calcBoundaryDF <- function(df, tolerance = 0.001, lengthFactor = 1.0, edgeFactor = 1.0) {
    .Call('marxan_rcpp_calcBoundaryDF', PACKAGE = 'marxan', df, tolerance, lengthFactor, edgeFactor)
}

rcpp_groupcombine <- function(group_sums) {
    .Call('marxan_rcpp_groupcombine', PACKAGE = 'marxan', group_sums)
}

rcpp_groupsum <- function(cat_vec, val_vec) {
    .Call('marxan_rcpp_groupsum', PACKAGE = 'marxan', cat_vec, val_vec)
}

rcpp_Polygons2PolySet <- function(polys, n_preallocate = 10000L) {
    .Call('marxan_rcpp_Polygons2PolySet', PACKAGE = 'marxan', polys, n_preallocate)
}

